name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: v1.18.2
      
    #- name: github
    #  run: git clone --branch v1.18.2 https://github.com/kubernetes/kubernetes.git
      
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Get workpath
      run: pwd

    #- name: 切换分支
    #  run: git checkout v1.18.2
      
    - name: Build
      run: make all WHAT=cmd/kubeadm GOFLAGS=-v

    - name: Get paGth
      run: find . -name kubeadm
      
    - name: Package
      run: mkdir myki && cp ./_output/local/bin/linux/amd64/kubeadm myki
      
    - uses: actions/upload-artifact@v1
      with:
        name: kubeadm-v1.18.2
        path: myki
    #- name: Copy file
    #  run: mkdir staging && cp _output/local/bin/linux/amd64/kubeadm staging
    #- name: Test
      #run: go test -v .
